[package]
name = "jsx-one"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_ecmascript = {git="https://github.com/jsx-one/parser.git", features=["parser"], version="0.46.0"}